# This is a basic workflow to help you get started with Actions

name: Conditional-if
on:
  push: 
    branches: main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "This runs only on main branch"
          # Add more commands here, each on a new line
          echo "You can add more commands in this block"
      - name: Print just the repo name       
       # run: echo "Repo name: ${GITHUB_REPOSITORY##*/}"
        shell: bash
      - name: Print just the repo name
        run: echo "Repo name:" $GITHUB_REPOSITORY  
