# This is a basic workflow to help you get started with Actions

name: Conditional-if 
on:
  push: 
    branches: main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main branch
        #if: github.ref == 'refs/heads/main'
        if: github.repository == 'vimaljay/Github-action123'
        run: |
          echo "This runs only on NON vims branch"
          # Add more commands here, each on a new line
          echo "You can add more commands in this block"
      - name: Print just the repo name       
        run: echo github.repository
        shell: bash
      - name: Print just the repo name
        run: echo "Repo name:" $GITHUB_REPOSITORY  
