name: my-first23adsasd
on:
 # push:
  #  branches:
   #    - main
  workflow_dispatch:
    inputs:
      name:
        description: "type your name"
        required: true
        default: "World"
jobs:
    greetings:
      runs-on: ubuntu-latest
      steps:
      - name: Print data
        run: |
          echo "Input guy:${{github.event.inputs.name}}"
         #echo "actual guy:${{github.actor}}"
     
